project_id = "klekjfcxxhihaufmwsaq"

[auth]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false

[functions.telegram-webhook]
verify_jwt = false

[functions.setup-webhook]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.payment-webhook]
verify_jwt = false

[functions.process-downsell]
verify_jwt = false

[functions.send-mailing]
verify_jwt = false

[functions.send-channel-message]
verify_jwt = false

[functions.admin-broadcast]
verify_jwt = true

[functions.linkter-api]
verify_jwt = true

[functions.apply-scheduled-prices]
verify_jwt = false

[functions.bot-health-check]
verify_jwt = false

[functions.apply-price-rules]
verify_jwt = false

[functions.contingency-redirect]
verify_jwt = false

[functions.revant-webhook]
verify_jwt = false

[functions.check-pending-payments]
verify_jwt = false


[functions.sales-widget]
verify_jwt = false

[functions.custom-link-redirect]
verify_jwt = false

[functions.broadcast-status-email]
verify_jwt = true

[functions.notify-users-email]
verify_jwt = true

[functions.sync-revantpay-demo]
verify_jwt = true

[functions.validate-revant-key]
verify_jwt = true
